apply plugin: 'com.android.application'

android {

    defaultConfig {
        applicationId "io.straas.android.sdk.demo"
        minSdkVersion 18
        compileSdk 34
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

    signingConfigs {
        debug {
            storeFile file("../debug.keystore")
        }
    }

    buildTypes {
        debug {
            manifestPlaceholders = [straas_client_id: "$your_debug_client_id"]
            signingConfig signingConfigs.debug
        }
        release {
            manifestPlaceholders = [straas_client_id: "$your_release_client_id"]
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    dataBinding {
        enabled = true
    }
    namespace 'io.straas.android.sdk.demo'
}

dependencies {
    implementation project (":SampleMediaCore")
    implementation project (":SampleMessaging")
    implementation project (":SampleStreaming")
}
